#define DISABLE_ERRNO
#define DISABLE_MLOCKALL
#define DISABLE_NUMA
#define DISABLE_PRIORITY_AND_POLICY
#define DISABLE_CLI_FLUSH
#define USE_PTHREAD_SELF_INSTEAD_OF_GETTID_SYSCALL
#define DISABLE_CPU_ZERO_AND_ONE_MACROS
#define DISABLE_THREAD_AFFINITY
#define DISABLE_MODE_CYCLIC
#define DISABLE_MODE_ITIMER
#define DISABLE_PRCTL
#define DISABLE_SIGNAL_ALARMS
#define DISABLE_PTHREAD_KILL
#define DISABLE_PTHREAD_ATTR
#define SET_MAX_CPU_CORES 32
