#!/bin/sh

# This script is configured to run a cyclictest under load for 1 hour. The
# output generated by hackbench is written to logfiles in the same working
# directory.
#
# Usage:
# ./run_cyclic.sh

# Variables to configure

# Sorted list of cores in ascending order
CORE_LIST="4 5 6 7"
# Number of loops each pair of hackbench processes is executing
NUM_LOOPS=200000

LC_ALL=C
export LC_ALL

NUM_CORES=$(printf "$CORE_LIST" | wc -w)

for core in $CORE_LIST
do
	#taskset -c $core hackbench -s 512 -l $NUM_LOOPS -g 64 -f 8 2>&1 >hackbench_${core}.log &
	#printf "hackbench[$!] started on core $core\n"
    printf "hackbench started\n"
done

#sudo cyclictest -a $(printf "$CORE_LIST" | cut -d ' ' -f 1)-$(printf "$CORE_LIST" | cut -d ' ' -f $NUM_CORES) -t $NUM_CORES -m -p 90 -i 100 -h 10000 --histfile load_interval.txt -D 60m
sudo ./cyclictest -a $(printf "$CORE_LIST" | cut -d ' ' -f 1)-$(printf "$CORE_LIST" | cut -d ' ' -f $NUM_CORES) -t $NUM_CORES -m -p 90 -i 100 -h 10000 -D 1m --histfile output.txt